// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seamqbwkcsalpkxxmoez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlYW1xYndrY3NhbHBreHhtb2V6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTY0MjksImV4cCI6MjA1OTE3MjQyOX0.PRqawTdFfRCVcgtwUl3PhR0K8MnGi6ibq3EAj-a-UCg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);